# Generated by dotstyle from theme/templates/alacritty.toml.tpl — do not edit.
# Imported from .config/alacritty/alacritty.toml.

[font]
size = {{ font_size }}
normal.family = "{{ font_family }}"
bold.family = "{{ font_family }}"
italic.family = "{{ font_family }}"

[colors.primary]
background = "{{ background }}"
foreground = "{{ foreground }}"

[colors.cursor]
text = "{{ background }}"
cursor = "{{ cursor }}"

[colors.vi_mode_cursor]
text = "{{ background }}"
cursor = "{{ cursor }}"

[colors.selection]
text = "{{ selection_foreground }}"
background = "{{ selection_background }}"

[colors.search.matches]
foreground = "{{ background }}"
background = "{{ yellow }}"

[colors.search.focused_match]
foreground = "{{ background }}"
background = "{{ red }}"

[colors.footer_bar]
foreground = "{{ background }}"
background = "{{ foreground }}"

[colors.normal]
black = "{{ color0 }}"
red = "{{ color1 }}"
green = "{{ color2 }}"
yellow = "{{ color3 }}"
blue = "{{ color4 }}"
magenta = "{{ color5 }}"
cyan = "{{ color6 }}"
white = "{{ color7 }}"

[colors.bright]
black = "{{ color8 }}"
red = "{{ color9 }}"
green = "{{ color10 }}"
yellow = "{{ color11 }}"
blue = "{{ color12 }}"
magenta = "{{ color13 }}"
cyan = "{{ color14 }}"
white = "{{ color15 }}"
