# Generated by dotstyle from theme/templates/dunst.conf.tpl — do not edit.
# Loaded as a drop-in from .config/dunst/dunstrc.d/, which dunst reads after
# dunstrc, so these win over anything set there.

[global]
    frame_color = "{{ accent }}"
    separator_color = frame
    font = {{ font_family }} {{ ui_font_size }}

[urgency_low]
    background = "{{ background }}"
    foreground = "{{ dark_foreground }}"
    frame_color = "{{ muted }}"
    timeout = 5

[urgency_normal]
    background = "{{ background }}"
    foreground = "{{ foreground }}"
    frame_color = "{{ accent }}"
    timeout = 8

[urgency_critical]
    background = "{{ background }}"
    foreground = "{{ bright_foreground }}"
    frame_color = "{{ red }}"
    timeout = 0
