# Generated by dotstyle from theme/templates/fish_colors.fish.tpl — do not edit.
# Sourced from .config/fish/conf.d/dotstyle.fish.

set -g fish_color_normal {{ foreground_strip }}
set -g fish_color_command {{ blue_strip }}
set -g fish_color_keyword {{ magenta_strip }}
set -g fish_color_quote {{ green_strip }}
set -g fish_color_redirection {{ cyan_strip }}
set -g fish_color_end {{ orange_strip }}
set -g fish_color_error {{ red_strip }}
set -g fish_color_param {{ light_foreground_strip }}
set -g fish_color_comment {{ muted_strip }}
set -g fish_color_selection --background={{ selection_background_strip }}
set -g fish_color_search_match --background={{ selection_background_strip }}
set -g fish_color_operator {{ cyan_strip }}
set -g fish_color_escape {{ magenta_strip }}
set -g fish_color_autosuggestion {{ muted_strip }}
set -g fish_color_cwd {{ yellow_strip }}
set -g fish_color_user {{ green_strip }}
set -g fish_color_host {{ blue_strip }}

set -g fish_pager_color_progress {{ muted_strip }}
set -g fish_pager_color_prefix {{ cyan_strip }}
set -g fish_pager_color_completion {{ foreground_strip }}
set -g fish_pager_color_description {{ muted_strip }}
set -g fish_pager_color_selected_background --background={{ selection_background_strip }}
