# Generated by dotstyle from theme/templates/ghostty.tpl — do not edit.
# Loaded from .config/ghostty/config.ghostty through the theme.ghostty link.

font-family = {{ font_family }}
font-size = {{ font_size }}

foreground = {{ foreground }}
background = {{ background }}
selection-foreground = {{ selection_foreground }}
selection-background = {{ selection_background }}

cursor-color = {{ bright_foreground }}
cursor-text = {{ background }}

palette = 0={{ background }}
palette = 1={{ red }}
palette = 2={{ green }}
palette = 3={{ yellow }}
palette = 4={{ blue }}
palette = 5={{ magenta }}
palette = 6={{ cyan }}
palette = 7={{ foreground }}
palette = 8={{ muted }}
palette = 9={{ bright_red }}
palette = 10={{ bright_green }}
palette = 11={{ bright_yellow }}
palette = 12={{ bright_blue }}
palette = 13={{ bright_magenta }}
palette = 14={{ bright_cyan }}
palette = 15={{ bright_foreground }}
