# Generated by dotstyle from theme/templates/hyprland.conf.tpl — do not edit.
# Included from .config/hypr/hyprland.conf, in place of the gaps/border/color
# constants .config/hypr/looknfeel.conf and gruvbox.conf used to hardcode.
# Keybindings live in bindings.conf and are never touched by theming.

general {
    gaps_in = {{ gaps }}
    gaps_out = {{ gaps }}
    border_size = {{ border_width }}
    col.active_border = rgba({{ accent_strip }}ff)
    col.inactive_border = rgba({{ muted_strip }}cc)
}

# hy3's tabbed/stacked group headers, themed to match — the same accent sway
# uses for client.focused's border.
plugin {
    hy3 {
        tabs {
            col.active = rgba({{ accent_strip }}ff)
            col.active.border = rgba({{ accent_strip }}ff)
        }
    }
}
