/* Generated by dotstyle from theme/templates/rofi.rasi.tpl — do not edit.
 * Imported from .config/rofi/config.rasi. Keeps the same variable names the
 * hand-written gruvbox palette used, so the rest of config.rasi is unchanged. */

* {
    highlight: bold italic;
    scrollbar: true;

    font: "{{ font_family }} {{ ui_font_size }}";

    background:                  {{ background }};
    background-color:            @background;
    foreground:                  {{ foreground }};
    border-color:                {{ muted }};
    separatorcolor:              @border-color;
    scrollbar-handle:            @border-color;

    normal-background:           @background;
    normal-foreground:           @foreground;
    alternate-normal-background: {{ lighter_background }};
    alternate-normal-foreground: @foreground;
    selected-normal-background:  {{ accent }};
    selected-normal-foreground:  {{ background }};

    active-background:           {{ yellow }};
    active-foreground:           {{ background }};
    alternate-active-background: @active-background;
    alternate-active-foreground: @active-foreground;
    selected-active-background:  {{ bright_yellow }};
    selected-active-foreground:  @active-foreground;

    urgent-background:           {{ red }};
    urgent-foreground:           {{ background }};
    alternate-urgent-background: @urgent-background;
    alternate-urgent-foreground: @urgent-foreground;
    selected-urgent-background:  {{ bright_red }};
    selected-urgent-foreground:  @urgent-foreground;
}
