# Generated by dotstyle from theme/templates/swaylock.conf.tpl — do not edit.
# Read by dot-lock via `swaylock -C`.

font={{ font_family }}
font-size={{ ui_font_size }}

indicator-radius=110
indicator-thickness={{ border_width }}
indicator-caps-lock

color={{ background_strip }}
inside-color={{ background_strip }}
inside-clear-color={{ background_strip }}
inside-ver-color={{ background_strip }}
inside-wrong-color={{ background_strip }}

ring-color={{ muted_strip }}
ring-clear-color={{ yellow_strip }}
ring-ver-color={{ accent_strip }}
ring-wrong-color={{ red_strip }}

key-hl-color={{ accent_strip }}
bs-hl-color={{ red_strip }}
caps-lock-key-hl-color={{ yellow_strip }}
caps-lock-bs-hl-color={{ red_strip }}

text-color={{ foreground_strip }}
text-clear-color={{ foreground_strip }}
text-ver-color={{ accent_strip }}
text-wrong-color={{ red_strip }}

line-color={{ background_strip }}
line-clear-color={{ background_strip }}
line-ver-color={{ background_strip }}
line-wrong-color={{ background_strip }}

separator-color={{ background_strip }}
layout-bg-color={{ background_strip }}
layout-border-color={{ muted_strip }}
layout-text-color={{ foreground_strip }}
