# Generated by dotstyle from theme/templates/sway.conf.tpl — do not edit.
# Included from .config/sway/config. Keybindings live there and are never
# touched by theming.

gaps inner {{ gaps }}
default_border pixel {{ border_width }}
default_floating_border pixel {{ border_width }}

#                       border            background        text              indicator         child_border
client.focused          {{ accent }} {{ accent }} {{ background }} {{ accent }} {{ accent }}
client.focused_inactive {{ muted }} {{ muted }} {{ foreground }} {{ muted }} {{ muted }}
client.unfocused        {{ muted }} {{ muted }} {{ dark_foreground }} {{ muted }} {{ muted }}
client.urgent           {{ red }} {{ red }} {{ background }} {{ red }} {{ red }}
client.placeholder      {{ background }} {{ background }} {{ foreground }} {{ background }} {{ background }}
client.background       {{ background }}

bar {
    position {{ bar_position }}
    # dot-bar rather than i3blocks directly: i3blocks dies across suspend and
    # sway never respawns a status command that exits, so the bar reads
    # "[error reading from status command]" until sway restarts.
    status_command dot-bar
    font pango:{{ font_family }} {{ ui_font_size }}
    height {{ bar_height }}

    colors {
        background {{ background }}
        statusline {{ foreground }}
        separator  {{ muted }}

        #                  border            background        text
        focused_workspace  {{ accent }} {{ accent }} {{ background }}
        active_workspace   {{ lighter_background }} {{ lighter_background }} {{ foreground }}
        inactive_workspace {{ lighter_background }} {{ lighter_background }} {{ dark_foreground }}
        urgent_workspace   {{ red }} {{ red }} {{ background }}
        binding_mode       {{ yellow }} {{ yellow }} {{ background }}
    }
}

# --- Session daemons ---
# One line, because sway's config lexer strips quotes before handing the command
# to sh, which mangles anything with nested quoting. dot-session restarts the
# idle daemon and the clipboard watcher, each guarded so
# that exec_always re-running on every reload cannot stack duplicates.
exec_always dot-session restart
