# Generated by dotstyle from theme/templates/borders.sh.tpl — do not edit.
# Window borders on macOS (JankyBorders), started by .config/aerospace/aerospace.toml.
# Mirrors client.focused / client.unfocused from sway.conf.

exec borders \
    style=square \
    width=4.0 \
    active_color=0xffe68e0d \
    inactive_color=0xff333333
