# Generated by dotstyle from theme/templates/fish_colors.fish.tpl — do not edit.
# Sourced from .config/fish/conf.d/dotstyle.fish.

set -g fish_color_normal bebebe
set -g fish_color_command e68e0d
set -g fish_color_keyword D35F5F
set -g fish_color_quote FFC107
set -g fish_color_redirection bebebe
set -g fish_color_end c63d3d
set -g fish_color_error D35F5F
set -g fish_color_param 8a8a8d
set -g fish_color_comment 333333
set -g fish_color_selection --background=2a2a2a
set -g fish_color_search_match --background=2a2a2a
set -g fish_color_operator bebebe
set -g fish_color_escape D35F5F
set -g fish_color_autosuggestion 333333
set -g fish_color_cwd b91c1c
set -g fish_color_user FFC107
set -g fish_color_host e68e0d

set -g fish_pager_color_progress 333333
set -g fish_pager_color_prefix bebebe
set -g fish_pager_color_completion bebebe
set -g fish_pager_color_description 333333
set -g fish_pager_color_selected_background --background=2a2a2a
