# Syntax-highlighting colors follow the active dotstyle theme.
# Regenerated by `dotstyle`; see dotfiles/theme/templates/fish_colors.fish.tpl.
set -l dotstyle_colors /home/ren/workspace/dotfiles/theme/current/fish_colors.fish
test -r $dotstyle_colors; and source $dotstyle_colors
