#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config external_bar               all:40:0
yabai -m config mouse_follows_focus          on 
yabai -m config focus_follows_mouse          on 
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off 
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on 
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffcba6f7
yabai -m config normal_window_border_color   0x00000000
yabai -m config insert_feedback_color        0xfff9e2af
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on 
yabai -m config mouse_modifier               cmd 
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                     bsp
yabai -m config top_padding                10
yabai -m config bottom_padding             10
yabai -m config left_padding               10
yabai -m config right_padding              10
yabai -m config window_gap                 10 

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off

# setup spaces
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 1
setup_space 2 2
setup_space 3 3
setup_space 4 4
setup_space 5 5
setup_space 6 6

# rules for apps and spaces
yabai -m rule --add app="^Brave$" space=^2
yabai -m rule --add app="^Safari$" space=^2
yabai -m rule --add app="^Firefox$" space=^2
yabai -m rule --add app="^Parallels$" space=^4
yabai -m rule --add app="^Telegram$" space=5
yabai -m rule --add app="^Music$" space=6
yabai -m rule --add app="^Spotify$" space=6

echo "yabai configuration loaded.."
