exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE DESKTOP_SESSION
exec-once = systemctl --user start graphical-session.target
exec-once = /usr/libexec/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = waybar & hyprpaper
exec-once = hyprpm reload -n
exec-once = wlsunset -T 4800 &
exec-once = makoctl mode -t do-not-disturb
exec-once = swaybg -i $HOME/Sync/Pictures/background.png &
exec-once = ~/.startup
exec-once = gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11'
exec-once = gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans 11'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono 11'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
