# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options = caps:super
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
        accel_profile = adaptive
        sensitivity = 0.5
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
    workspace_swipe_invert = false
    workspace_swipe_cancel_ratio = 0.5
}

# Per-device: trackpoint
device {
    name = tpps/2-elan-trackpoint
    sensitivity = 0.9
}
