# GitHub Actions CI Template for NixOS Configurations
#
# This workflow checks NixOS configurations on every push and pull request
# Place this file in .github/workflows/nixos-check.yml

name: NixOS Configuration Check

on:
  push:
    branches: [ main, master ]
    paths:
      - 'nixos/**'
      - '.github/workflows/nixos-check.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'nixos/**'

jobs:
  check:
    name: Check NixOS Configurations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Cachix (optional - speeds up builds)
        uses: cachix/cachix-action@v12
        with:
          name: mycache  # Replace with your cachix cache name
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      
      - name: Check flake
        working-directory: nixos
        run: |
          nix flake check --all-systems --no-build
      
      - name: Format check
        working-directory: nixos
        run: |
          nix fmt -- --check .
        continue-on-error: true  # Don't fail on formatting issues
      
      - name: Build all configurations
        working-directory: nixos
        run: |
          # Build each host configuration
          nix build .#nixosConfigurations.lenovo-t14s-x1e.config.system.build.toplevel
          # Add more hosts as needed
      
      - name: Check for eval errors
        working-directory: nixos
        run: |
          nix eval .#nixosConfigurations --apply builtins.attrNames

  build-iso:
    name: Build Installer ISOs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        host: [lenovo-t14s-x1e]
        # Add more hosts here
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Build ISO
        working-directory: nixos
        run: |
          # Note: This may take a long time and use a lot of disk space
          # Consider only building on release tags
          nix build .#packages.x86_64-linux.${{ matrix.host }}-iso || \
          nix build .#packages.aarch64-linux.${{ matrix.host }}-iso
      
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.host }}-installer-iso
          path: result/iso/*.iso
          retention-days: 7

  docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: 'nixos'
      
      - name: Check for TODO/FIXME
        run: |
          cd nixos
          if grep -r "TODO\|FIXME" --include="*.nix" --include="*.md" .; then
            echo "Found TODO/FIXME items"
            exit 0  # Don't fail, just notify
          fi

# Optional: Deployment job (only on main branch)
# deploy:
#   name: Deploy to Server
#   runs-on: ubuntu-latest
#   needs: [check, build-iso]
#   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#   
#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#     
#     - name: Install Nix
#       uses: cachix/install-nix-action@v24
#     
#     - name: Deploy via SSH
#       env:
#         SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
#       run: |
#         eval $(ssh-agent)
#         ssh-add - <<< "$SSH_KEY"
#         nixos-rebuild switch --flake .#hostname --target-host user@server
