#!/usr/bin/env bash

# Set up Sway and SwayFX as login sessions next to COSMIC.
#
# - installs sway from apt (skipped with --no-apt)
# - checks that swayfx is available (it comes from home-manager, not apt)
# - installs session wrappers that export the Wayland environment
# - adds "Sway (session)" and "SwayFX" entries to wayland-sessions for
#   display managers such as cosmic-greeter
# - adds the same sessions to lemurs when /etc/lemurs exists
#
# Usage: sudo scripts/setup-sway.sh [--no-apt]
# ROOT=/some/dir installs into a staging root (for testing, no sudo needed).

set -e

ROOT="${ROOT:-}"
PREFIX="${PREFIX:-/usr/local}"
INSTALL_APT=1

for arg in "$@"
do
    case "$arg" in
        --no-apt) INSTALL_APT=0 ;;
        -h|--help) sed -n '3,15p' "$0"; exit 0 ;;
        *) echo "$0: unknown argument: $arg" >&2; exit 1 ;;
    esac
done

if [ -z "$ROOT" ] && [ "$(id -u)" != 0 ]
then
    echo "$0: run as root (sudo), or set ROOT= to install into a staging dir" >&2
    exit 1
fi

# The user whose swayfx and sway config the sessions use
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"

if [ "$INSTALL_APT" = 1 ] && [ -z "$ROOT" ]
then
    if ! dpkg -s sway >/dev/null 2>&1
    then
        apt-get install -y sway swaybg
    fi
fi

if ! command -v sway >/dev/null 2>&1 && [ ! -x /usr/bin/sway ]
then
    echo "warning: sway is not installed, the Sway session will not start" >&2
fi

if [ ! -x "$TARGET_HOME/.nix-profile/bin/swayfx" ]
then
    echo "warning: $TARGET_HOME/.nix-profile/bin/swayfx not found;" >&2
    echo "         run home-manager switch (dotfiles nix/linux/programs.nix) first" >&2
fi

BIN_DIR="$ROOT$PREFIX/bin"
SESSIONS_DIR="$ROOT$PREFIX/share/wayland-sessions"
mkdir -p "$BIN_DIR" "$SESSIONS_DIR"

# write_wrapper NAME DESKTOP CONFIG COMMAND
# CONFIG and COMMAND are expanded at session start, as the logged-in user.
write_wrapper() {
    cat > "$BIN_DIR/$1" <<EOF
#!/usr/bin/env bash
# Generated by cosmic-epoch/scripts/setup-sway.sh
set -e

export XDG_CURRENT_DESKTOP="\${XDG_CURRENT_DESKTOP:=sway}"
export XDG_SESSION_TYPE="\${XDG_SESSION_TYPE:=wayland}"
export DESKTOP_SESSION="\${DESKTOP_SESSION:=$2}"
export _JAVA_AWT_WM_NONREPARENTING=1
export GDK_BACKEND=wayland,x11
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_ENABLE_HIGHDPI_SCALING=1

config="$3"
if [ -f "\$config" ]
then
    exec $4 -c "\$config"
fi
exec $4
EOF
    chmod 755 "$BIN_DIR/$1"
}

write_wrapper sway-session sway '$HOME/.config/sway/config' 'sway'
# swayfx is a nixGL wrapper in the user's nix profile, not on the greeter's PATH
write_wrapper swayfx-session swayfx '$HOME/.config/sway/config-fx' '"$HOME/.nix-profile/bin/swayfx"'

cat > "$SESSIONS_DIR/sway-session.desktop" <<EOF
[Desktop Entry]
Name=Sway (session)
Comment=Sway with the Wayland session environment
Exec=$PREFIX/bin/sway-session
Type=Application
DesktopNames=sway;wlroots
EOF

cat > "$SESSIONS_DIR/swayfx-session.desktop" <<EOF
[Desktop Entry]
Name=SwayFX
Comment=SwayFX (sway with blur and effects) under nixGL
Exec=$PREFIX/bin/swayfx-session
Type=Application
DesktopNames=sway;wlroots
EOF

if [ -d /etc/lemurs ]
then
    LEMURS_DIR="$ROOT/etc/lemurs/wayland"
    mkdir -p "$LEMURS_DIR"
    for name in sway swayfx
    do
        printf '#!/usr/bin/env bash\nexec %s/bin/%s-session\n' "$PREFIX" "$name" > "$LEMURS_DIR/$name"
        chmod 755 "$LEMURS_DIR/$name"
    done
fi

echo "Installed:"
echo "  $BIN_DIR/sway-session, $BIN_DIR/swayfx-session"
echo "  $SESSIONS_DIR/sway-session.desktop, $SESSIONS_DIR/swayfx-session.desktop"
[ -d /etc/lemurs ] && echo "  $ROOT/etc/lemurs/wayland/{sway,swayfx}"
exit 0
