import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[shell]
program = "/home/ren/.nix-profile/bin/fish"

[font]
size = 16
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
