import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[shell]
program = "/home/ren/.nix-profile/bin/fish"

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
